version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: python chat.py
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mongodb
      - valkey
      - vector-db

  valkey:
    image: valkey/valkey
    ports:
      - "6379:6379"

  vector-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:


# neo4j:
#   image:neo4j:latest
#   ports:
#     -7474:7474
#     -7687:7684
#     volumes:
#     mongodb_data:
#     neo4j_data